// Automatically generated by astro-icon
// 4915cebcbac9a5c6655efaadbf7898609c5ea443ffd637058b04b734ee252c79

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "abstractly-logo"
		| "arrow-down"
		| "arrow-right"
		| "burger-menu"
		| "calendar-event"
		| "calendar-line"
		| "calendar-todo"
		| "checkbox-blank"
		| "checkbox-checked"
		| "email"
		| "github"
		| "instagram"
		| "linkedin"
		| "question-circle"
		| "star"
		| "x";
}