// Automatically generated by astro-icon
// 61c7528a5e2973cab39c5f53b55d616ab7bf7d46c8241a5e6e234ef55b14882c

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "abstractly-logo"
		| "arrow-right"
		| "burger-menu"
		| "github"
		| "instagram"
		| "linkedin"
		| "star"
		| "x";
}