// Automatically generated by astro-icon
// 80d607fe8f3685ce590dcc0f0742ec67ff556d339b55fd07239b143a022f14ba

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "abstractly-logo"
		| "arrow-down"
		| "arrow-left"
		| "arrow-right"
		| "burger-menu"
		| "calendar-event"
		| "calendar-line"
		| "calendar-todo"
		| "checkbox-blank"
		| "checkbox-checked"
		| "email"
		| "github"
		| "globe"
		| "instagram"
		| "linkedin"
		| "lock"
		| "mist"
		| "question-circle"
		| "star"
		| "x";
}