name: Deploy to GitHub Pages

on:
  # Déclenche le workflow à chaque push vers la branche `main`
  push:
    branches: [ main ]
  # Permet d'exécuter le workflow manuellement depuis l'onglet Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      # Étape 2 : Installer les dépendances et construire le site Astro
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: . # Racine du projet Astro (facultatif si vous êtes à la racine)
          node-version: 20 # Version de Node.js (par défaut : 20)
          package-manager: npm # Gestionnaire de paquets (npm par défaut)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # Étape 3 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
